name: Build for Mac

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        version: ['5.14.2']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 5.14.2-fix

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.version }}

      - name: Build
        run: |
          mkdir build
          cd build
          qmake CONFIG+=release ../qtserialbus.pro
          make
        shell: bash
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libqtpeakcanbus.dylib
          path: build/plugins/canbus/libqtpeakcanbus.dylib
